version: 2.1
filter:
  branches:
    only:
      - main
jobs:
  build:
    docker:
      - image: circleci/node:12.9.1-browsers
    steps:
      - checkout
      - run: cd ./my-app/ && npm install
      - run:
          command: cd ./my-app/ && npm start
          background: true
  test:
    docker:
      - image: circleci/node:12.9.1-browsers
    steps:
      - checkout
      - run: cd ./my-app/ && npm install
      - run: cd ./my-app/ && npm run test
workflows:
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
