orbs:
  react: 'thefrontside/react@dev:alpha'
version: 2.1
workflows:
  push:
    jobs:
      - run: cd ./my-app/
      - react/install
      - react/test:
          requires:
            - react/install
