version: 2.1
orbs:
  node: circleci/node@4.2.1
filter:
  branches:
    only:
      - main
jobs:
  build:
    executor:
      name: node/default
    steps:
      - checkout
      - run: cd ./my-app/ && npm install
      - run:
          command: cd ./my-app/ && npm start
          background: true
  test:
    executor:
      name: node/default
    steps:
      - checkout
      - run: cd ./my-app/ && npm install
      - run: cd ./my-app/ && npm run test
workflows:
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
