version: 2.1
orbs:
  node: circleci/node@1.1.0
filter:
  branches:
    only:
      - main
jobs:
  build:
    executor:
      name: node/default
      tag: '10.4'
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: cd ./my-app/ && npm install
      - run:
          command: cd ./my-app/ && npm start
          background: true
  test:
    steps:
      - run: cd ./my-app/ && npm run test
workflows:
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build